version: '3'
services:
    nginx:
        image: nginx
        # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        # network_mode: host
        ports:
            - 80:80
            # - 443:443
        environment:
            # - HOST_IP=host.docker.internal
            - NGINX_PORT=80
            - NGINX_GENERATE_DEFAULT_VHOST=false
            - TZ=Asia/Seoul
        volumes:
            - /Users/seotory/Workspace/docker-nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
            - /Users/seotory/Workspace/docker-nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
            # - /Users/seotory/Workspace/we/conf.d/site.conf:/etc/nginx/conf.d/mysite.template
        # extra_hosts:
        #     - host.docker.internal
